apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-learner
  labels:
    app: card-learner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-learner
  template:
    metadata:
      labels:
        app: card-learner
    spec:
      containers:
        - name: card-learner
          image: ghcr.io/janne6565/card-learner:sha-607f39d
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: card-learner-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
