apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: card-learner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - card-learner.jannekeipert.de
      secretName: card-learner-tls
  rules:
    - host: card-learner.jannekeipert.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: card-learner
                port:
                  number: 80
